security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\Trainer:
            algorithm: bcrypt

    providers:
        trainers:
            entity:
                class: App\Entity\Trainer
                property: email

    firewalls:
        main:
            lazy: true
            provider: trainers
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

