index:
    path: /
    controller: App\Controller\HomeController::index

trainer_registration:
  path: /register
  controller: App\Controller\RegistrationController::register

registration_success:
  path: /registration/success
  controller: App\Controller\RegistrationController::success

login:
    path: /login
    controller: App\Controller\LoginController::login

logout:
    path: /logout
    controller: App\Controller\LoginController::logout

Home:
    path: /home
    controller: App\Controller\HomeController::index

first_sucess:
  path: /registration/first_login
  controller: App\Controller\RefPokemonType::success

add_pokemon:
  path: /toto
  controller: App\Controller\RefPokemonType::addPokemon

myPokemon:
  path: /myPokemon
  controller: App\Controller\TrainerController::myPokemon

train:
  path: /train
  controller: App\Controller\TrainerController::train
  methods: [POST]

realease:
  path: /release
  controller: App\Controller\TrainerController::release
  methods: [POST]

sell:
  path: /sell
  controller: App\Controller\TrainerController::sell
  methods: [POST]


