index:
    path: /
    controller: App\Controller\HomeController::index
trainer_registration:
  path: /register
  controller: App\Controller\RegistrationController::register

registration_success:
  path: /registration/success
  controller: App\Controller\RegistrationController::success

login:
    path: /login
    controller: App\Controller\LoginController::login

Home:
    path: /home
    controller: App\Controller\HomeController::index

first_sucess:
  path: /registration/first_login
  controller: App\Controller\RefPokemonType::success